# Disable TLS validation
quarkus.tls.trust-all=true

# OpenTelemetry
quarkus.otel.enabled=false

# Dev Services
quarkus.devservices.enabled=false
quarkus.compose.devservices.enabled=false

# Kafka
quarkus.kafka.devservices.enabled=false

# Apache Camel Kafka Component
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.securityProtocol=SASL_PLAINTEXT
camel.component.kafka.saslMechanism=SCRAM-SHA-512
camel.component.kafka.saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-admin" password="openshift" serviceName="kafka";
camel.component.kafka.shutdownTimeout=5000
camel.component.kafka.clientId=syslog-forwarder

# Application
kafka.topic=test