loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.18.2
camel.jbang.springBootVersion=3.5.13
camel.jbang.quarkusVersion=3.31.3
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.jbang.javaVersion=21
camel.jbang.kameletsVersion=4.18.1
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.18.2
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.18.1
dependency=mvn\:org.apache.camel\:camel-netty\:4.18.2
