# Diasable TLS validation
quarkus.tls.trust-all=true

# OpenTelemetry
quarkus.otel.enabled=true

# Kubernetes
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.config-maps=kafka-http-sink-connector-config

# OpenShift
quarkus.openshift.build-strategy=docker

# OIDC
quarkus.oidc-client.enabled=${HTTP_AUTH_OIDC:flase}
quarkus.oidc-client.auth-server-url=${HTTP_AUTH_OIDC_SERVER_URL}
quarkus.oidc-client.client-id=${HTTP_AUTH_OIDC_CLIENT_ID}
quarkus.oidc-client.credentials.secret=${HTTP_AUTH_OIDC_SECRET}
quarkus.oidc-client.grant.type=client

# Camel Kafka Component
camel.component.kafka.brokers=${KAFKA_BROKERS:test}
camel.component.kafka.saslMechanism=SCRAM-SHA-512
camel.component.kafka.securityProtocol=SASL_PLAINTEXT
camel.component.kafka.saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:kafka-admin}" password="${KAFKA_PASSWORD:openshift}" serviceName="kafka";

# Application
kafka.topic.incoming=${KAFKA_TOPIC_INCOMING:test}
kafka.topic.dlq=${KAFKA_TOPIC_DLQ:dlq}

http.url=${HTTP_URL}
http.method=${HTTP_METHOD:POST}
http.secure=${HTTP_SECURE}
http.content-type=${HTTP_CONTENT_TYPE:application/json}
http.auth=${HTTP_AUTH:none}
http.auth.basic.username=${HTTP_AUTH_BASIC_USERNAME:test}
http.auth.basic.password=${HTTP_AUTH_BASIC_PASSWORD:test}