# Diasable TLS validation
quarkus.tls.trust-all=true

# OpenTelemetry
quarkus.otel.enabled=true

# Kubernetes
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.config-maps=kafka-http-sink-connector-config

# OpenShift
quarkus.openshift.build-strategy=docker

# OIDC
quarkus.oidc-client.enabled=${http_auth_oidc:true}
quarkus.oidc-client.auth-server-url=${http_auth_oidc_server_url}
quarkus.oidc-client.client-id=${http_auth_oidc_client_id}
quarkus.oidc-client.credentials.secret=${http_auth_oidc_secret}
quarkus.oidc-client.grant.type=client

# Camel Kafka Component
camel.component.kafka.brokers=${kafka_brokers:test}
camel.component.kafka.saslMechanism=SCRAM-SHA-512
camel.component.kafka.securityProtocol=SASL_PLAINTEXT
camel.component.kafka.saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="${kafka_username:kafka-admin}" password="${kafka_password:openshift}" serviceName="kafka";

# Application
kafka.topic.incoming=${kafka_topic_incoming}
kafka.topic.dlq=${kafka_topic_dlq}

http.url=${http_url}
http.secure=${http_secure}
http.content-type=${http_content_type}
http.auth=${http_auth:oidc}
http.auth.basic.username=${http_auth_basic_username:test}
http.auth.basic.password=${http_auth_basic_password:test}