# Disable TLS validation
quarkus.tls.trust-all=true

# OpenTelemetry
quarkus.otel.enabled=false

# Dev Services
quarkus.devservices.enabled=false

quarkus.compose.devservices.enabled=false

# Kubernetes
quarkus.kubernetes-config.enabled=false
quarkus.kubernetes-client.devservices.enabled=false

# Keycloak
quarkus.keycloak.devservices.enabled=false

# Kafka
quarkus.kafka.devservices.enabled=false

# Apache Camel Kafka Component
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.securityProtocol=SASL_PLAINTEXT
camel.component.kafka.saslMechanism=SCRAM-SHA-512
camel.component.kafka.saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-admin" password="openshift" serviceName="kafka";
camel.component.kafka.shutdownTimeout=5000
camel.component.kafka.clientId=kafka-http-sink-connector

# HTTP
quarkus.wiremock.devservices.enabled=false
quarkus.wiremock.devservices.port=8280

# OIDC
quarkus.oidc-client.enabled=true
quarkus.oidc-client.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc-client.refresh-interval=1m
quarkus.oidc-client.client-id=quarkus-app
quarkus.oidc-client.credentials.secret=secret
quarkus.oidc-client.grant.type=client

quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus

# Application
kafka.topic.incoming=test
kafka.topic.dlq=dlq

http.url=http://localhost:8280/test
http.method=POST
http.secure=false
http.content-type=application/json
http.auth=oidc